version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: percona:ps-8
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: divelog
      MYSQL_PASSWORD: divelog
      MYSQL_DATABASE: divelog
      MYSQL_ROOT_PASSWORD: password