server:
  port: 8000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/divelog
    username: divelog
    password: divelog
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update